// Chronicle — static data: epochs, events, and zoom levels.

        // ============================================
        // DATA - EPOCHS
        // ============================================
        const epochs = [
            // Row 0 - Major geological/cosmic eras
            { id: "cosmic", title: "Kosmische Ära", start: -13800000000, end: -4600000000, color: "#8b5cf6", row: 0 },
            { id: "hadean", title: "Hadaikum", start: -4600000000, end: -4000000000, color: "#dc2626", row: 0 },
            { id: "archean", title: "Archaikum", start: -4000000000, end: -2500000000, color: "#10b981", row: 0 },
            { id: "proterozoic", title: "Proterozoikum", start: -2500000000, end: -540000000, color: "#3b82f6", row: 0 },
            { id: "phanerozoic", title: "Phanerozoikum", start: -540000000, end: 2025, color: "#ef4444", row: 0 },
            // Row 1 - Human prehistory and medieval
            { id: "paleolithic", title: "Altsteinzeit", start: -2500000, end: -10000, color: "#78716c", row: 1 },
            { id: "neolithic", title: "Jungsteinzeit", start: -10000, end: -3000, color: "#84cc16", row: 1 },
            { id: "bronze", title: "Bronzezeit", start: -3000, end: -1200, color: "#f59e0b", row: 1 },
            { id: "iron", title: "Eisenzeit", start: -1200, end: -500, color: "#6b7280", row: 1 },
            { id: "antiquity", title: "Antike", start: -500, end: 500, color: "#ef4444", row: 1 },
            { id: "medieval", title: "Mittelalter", start: 500, end: 1500, color: "#8b5cf6", row: 1 },
            { id: "modern", title: "Neuzeit", start: 1500, end: 2025, color: "#3b82f6", row: 1 },
            // Row 2 - Cultural/Art movements
            { id: "renaissance", title: "Renaissance", start: 1400, end: 1600, color: "#06b6d4", row: 2 },
            { id: "baroque", title: "Barock", start: 1600, end: 1750, color: "#d946ef", row: 2 },
            { id: "classicism", title: "Klassizismus", start: 1750, end: 1830, color: "#14b8a6", row: 2 },
            { id: "romanticism", title: "Romantik", start: 1800, end: 1850, color: "#f472b6", row: 3 },
            { id: "realism", title: "Realismus", start: 1840, end: 1880, color: "#78716c", row: 2 },
            { id: "impressionism", title: "Impressionismus", start: 1860, end: 1910, color: "#38bdf8", row: 3 },
            { id: "expressionism", title: "Expressionismus", start: 1905, end: 1930, color: "#ef4444", row: 2 },
            { id: "modernism", title: "Moderne", start: 1900, end: 1970, color: "#6366f1", row: 3 },
            { id: "postmodern", title: "Postmoderne", start: 1970, end: 2000, color: "#a855f7", row: 2 },
            { id: "digital", title: "Digital", start: 1990, end: 2025, color: "#3b82f6", row: 3 },
            // Row 3 - Political/Historical periods
            { id: "enlightenment", title: "Aufklärung", start: 1685, end: 1800, color: "#fbbf24", row: 2 },
            { id: "industrial", title: "Industrialisierung", start: 1760, end: 1914, color: "#64748b", row: 0 },
            { id: "ww1", title: "1. Weltkrieg", start: 1914, end: 1918, color: "#991b1b", row: 0 },
            { id: "interwar", title: "Zwischenkrieg", start: 1918, end: 1939, color: "#a16207", row: 0 },
            { id: "ww2", title: "2. Weltkrieg", start: 1939, end: 1945, color: "#7f1d1d", row: 0 },
            { id: "coldwar", title: "Kalter Krieg", start: 1947, end: 1991, color: "#1e40af", row: 0 }
        ];

        // ============================================
        // DATA - EVENTS (Expanded)
        // ============================================
        let events = [
            // Cosmic & Geological
            { id: 1, time: -13800000000, title: "Urknall", subtitle: "Beginn von allem", desc: "Der Urknall markiert den Beginn des Universums - Raum, Zeit, Materie und Energie entstehen in einer gewaltigen Explosion aus einem unendlich dichten Punkt.", cat: "ereignis", imp: 1 },
            { id: 2, time: -13400000000, title: "Erste Sterne", subtitle: "Kosmische Dämmerung", desc: "Die ersten Sterne entstehen aus Wasserstoff und Helium und beenden das dunkle Zeitalter des Universums.", cat: "wissenschaft", imp: 2 },
            { id: 3, time: -4600000000, title: "Erde entsteht", subtitle: "Unser Planet", desc: "Die Erde formt sich aus Gas und Staub um die junge Sonne durch Akkretion von Planetesimalen.", cat: "ereignis", imp: 1 },
            { id: 4, time: -4500000000, title: "Mond entsteht", subtitle: "Theia-Einschlag", desc: "Ein marsgroßer Protoplanet kollidiert mit der Erde, das herausgeschleuderte Material formt unseren Mond.", cat: "ereignis", imp: 2 },
            { id: 5, time: -3800000000, title: "Erstes Leben", subtitle: "Einzeller", desc: "In den Urmeeren entstehen die ersten prokaryotischen Lebensformen - ein Wunder der chemischen Evolution.", cat: "wissenschaft", imp: 1 },
            { id: 6, time: -2400000000, title: "Große Sauerstoffkatastrophe", subtitle: "Atmosphärenwandel", desc: "Cyanobakterien produzieren Sauerstoff, der die Atmosphäre grundlegend verändert und viele Lebensformen auslöscht.", cat: "wissenschaft", imp: 2 },
            { id: 7, time: -540000000, title: "Kambrische Explosion", subtitle: "Artenvielfalt", desc: "In nur 20 Millionen Jahren entstehen fast alle modernen Tierstämme - eine beispiellose evolutionäre Radiation.", cat: "wissenschaft", imp: 1 },
            { id: 8, time: -252000000, title: "Perm-Trias-Aussterben", subtitle: "Das große Sterben", desc: "Das schlimmste Massenaussterben der Erdgeschichte: 96% aller Meeresarten und 70% aller Landwirbeltiere sterben aus.", cat: "ereignis", imp: 1 },
            { id: 9, time: -66000000, title: "Dinosaurier Aussterben", subtitle: "Chicxulub-Asteroid", desc: "Ein 10km großer Asteroid schlägt in Mexiko ein und beendet die 165 Millionen Jahre währende Herrschaft der Dinosaurier.", cat: "ereignis", imp: 1 },

            // Human Evolution
            { id: 10, time: -7000000, title: "Menschenaffen-Vorfahren", subtitle: "Sahelanthropus", desc: "Die frühesten bekannten Hominiden lebten in Afrika und gingen bereits aufrecht.", cat: "wissenschaft", imp: 2 },
            { id: 11, time: -2500000, title: "Erste Steinwerkzeuge", subtitle: "Oldowan-Kultur", desc: "Homo habilis fertigt die ersten Steinwerkzeuge an - der Beginn der technologischen Evolution.", cat: "wissenschaft", imp: 2 },
            { id: 12, time: -1800000, title: "Homo erectus", subtitle: "Wanderungen", desc: "Homo erectus verlässt Afrika und besiedelt als erste Menschenart Eurasien.", cat: "wissenschaft", imp: 2 },
            { id: 13, time: -800000, title: "Feuernutzung", subtitle: "Kontrolle über Flammen", desc: "Menschen lernen, Feuer zu kontrollieren - ein entscheidender Schritt in der Kulturentwicklung.", cat: "wissenschaft", imp: 1 },
            { id: 14, time: -300000, title: "Homo Sapiens", subtitle: "Moderner Mensch", desc: "Der anatomisch moderne Mensch entsteht in Afrika - unsere direkte Abstammungslinie beginnt.", cat: "wissenschaft", imp: 1 },
            { id: 15, time: -70000, title: "Kognitive Revolution", subtitle: "Symbolisches Denken", desc: "Menschen entwickeln Sprache, abstrakte Kunst und komplexe soziale Strukturen.", cat: "wissenschaft", imp: 1 },
            { id: 16, time: -40000, title: "Höhlenmalerei", subtitle: "Erste Kunst", desc: "In Lascaux, Altamira und anderen Höhlen entstehen beeindruckende Kunstwerke, die von spirituellem Denken zeugen.", cat: "kultur", imp: 2 },
            { id: 17, time: -30000, title: "Aussterben der Neandertaler", subtitle: "Letzte Verwandte", desc: "Die letzten Neandertaler sterben aus - Homo sapiens bleibt als einzige Menschenart übrig.", cat: "wissenschaft", imp: 2 },
            { id: 18, time: -12000, title: "Ende der Eiszeit", subtitle: "Klimawandel", desc: "Die letzte Eiszeit endet, Gletscher schmelzen, der Meeresspiegel steigt um 120 Meter.", cat: "ereignis", imp: 2 },
            { id: 19, time: -10000, title: "Neolithische Revolution", subtitle: "Sesshaftigkeit", desc: "Menschen werden sesshaft, beginnen Ackerbau und Viehzucht - der größte Wandel der Menschheitsgeschichte.", cat: "ereignis", imp: 1 },

            // Ancient Civilizations
            { id: 20, time: -3500, title: "Erfindung der Schrift", subtitle: "Keilschrift in Sumer", desc: "In Mesopotamien entsteht die Schrift zur Buchführung - der Beginn der aufgezeichneten Geschichte.", cat: "wissenschaft", imp: 1 },
            { id: 21, time: -3100, title: "Vereinigung Ägyptens", subtitle: "König Narmer", desc: "Ober- und Unterägypten werden vereinigt, die pharaonische Zivilisation beginnt.", cat: "politik", imp: 2 },
            { id: 22, time: -2560, title: "Cheops-Pyramide", subtitle: "Weltwunder", desc: "Die Große Pyramide von Gizeh wird erbaut - 4.500 Jahre lang das höchste Bauwerk der Welt.", cat: "kultur", imp: 1 },
            { id: 23, time: -1754, title: "Codex Hammurabi", subtitle: "Erstes Gesetzbuch", desc: "Der babylonische König Hammurabi verfasst eines der ältesten erhaltenen Gesetzbücher der Welt.", cat: "politik", imp: 2 },
            { id: 24, time: -1500, title: "Vedische Schriften", subtitle: "Hinduismus", desc: "Die Veden, die ältesten religiösen Texte Indiens, werden verfasst.", cat: "kultur", imp: 2 },
            { id: 25, time: -1200, title: "Trojanischer Krieg", subtitle: "Mythos & Geschichte", desc: "Der legendäre Krieg zwischen Griechen und Trojanern - Grundlage der Ilias.", cat: "ereignis", imp: 2 },
            { id: 26, time: -776, title: "Olympische Spiele", subtitle: "Erste Olympiade", desc: "Die ersten gesamtgriechischen Spiele werden in Olympia zu Ehren des Zeus abgehalten.", cat: "kultur", imp: 2 },
            { id: 27, time: -753, title: "Gründung Roms", subtitle: "Romulus und Remus", desc: "Der Legende nach wird Rom durch Romulus gegründet - Beginn einer Weltmacht.", cat: "ereignis", imp: 2 },
            { id: 28, time: -551, title: "Konfuzius geboren", subtitle: "Chinesischer Philosoph", desc: "Der einflussreichste Denker Chinas, dessen Lehren bis heute das ostasiatische Denken prägen.", cat: "person", imp: 1 },
            { id: 29, time: -509, title: "Römische Republik", subtitle: "Ende der Königszeit", desc: "Rom wird zur Republik - Grundlage für spätere demokratische Systeme.", cat: "politik", imp: 2 },
            { id: 30, time: -500, title: "Buddha erlangt Erleuchtung", subtitle: "Siddhartha Gautama", desc: "Der Begründer des Buddhismus erreicht unter dem Bodhi-Baum das Nirvana.", cat: "person", imp: 1 },
            { id: 31, time: -490, title: "Schlacht bei Marathon", subtitle: "Perserkriege", desc: "Die Athener besiegen die persische Übermacht und retten die griechische Freiheit.", cat: "ereignis", imp: 2 },
            { id: 32, time: -469, title: "Sokrates geboren", subtitle: "Vater der Philosophie", desc: "Der Begründer der westlichen Philosophie, bekannt für seine maieutische Methode.", cat: "person", imp: 2 },
            { id: 33, time: -447, title: "Parthenon", subtitle: "Athen", desc: "Der Bau des Parthenon beginnt - Meisterwerk der klassischen griechischen Architektur.", cat: "kultur", imp: 2 },
            { id: 34, time: -427, title: "Platon geboren", subtitle: "Philosoph", desc: "Schüler des Sokrates, Lehrer des Aristoteles, Gründer der Akademie.", cat: "person", imp: 2 },
            { id: 35, time: -384, title: "Aristoteles geboren", subtitle: "Universalgelehrter", desc: "Der einflussreichste Denker der Antike, prägte die Wissenschaft für 2000 Jahre.", cat: "person", imp: 2 },
            { id: 36, time: -356, title: "Alexander der Große", subtitle: "Welteneroberer", desc: "Der makedonische Prinz wird geboren, der später das größte Reich der Antike erschaffen wird.", cat: "person", imp: 1 },
            { id: 37, time: -323, title: "Alexanders Tod", subtitle: "Babel", desc: "Alexander stirbt mit 32 Jahren in Babylon, sein Reich zerfällt in Diadochenreiche.", cat: "ereignis", imp: 2 },
            { id: 38, time: -264, title: "Erster Punischer Krieg", subtitle: "Rom vs. Karthago", desc: "Beginn der Kriege zwischen Rom und Karthago um die Vorherrschaft im Mittelmeer.", cat: "ereignis", imp: 2 },
            { id: 39, time: -221, title: "Qin Shihuangdi", subtitle: "Erster Kaiser Chinas", desc: "China wird erstmals vereinigt, die Chinesische Mauer wird erweitert.", cat: "politik", imp: 2 },
            { id: 40, time: -44, title: "Caesar ermordet", subtitle: "Iden des März", desc: "Julius Caesar wird im Senat von Verschwörern um Brutus erstochen - das Ende der Republik naht.", cat: "ereignis", imp: 1 },
            { id: 41, time: -31, title: "Schlacht bei Actium", subtitle: "Octavian vs. Antonius", desc: "Octavian besiegt Marcus Antonius und Kleopatra - Beginn des Römischen Kaiserreichs.", cat: "ereignis", imp: 2 },
            { id: 42, time: 0, title: "Zeitenwende", subtitle: "Jahr 0/1", desc: "Beginn unserer Zeitrechnung, basierend auf der Geburt Jesu Christi.", cat: "ereignis", imp: 1 },
            { id: 43, time: 30, title: "Kreuzigung Jesu", subtitle: "Jerusalem", desc: "Die Kreuzigung Jesu von Nazareth wird zum Ursprung des Christentums.", cat: "ereignis", imp: 1 },
            { id: 44, time: 79, title: "Vesuv-Ausbruch", subtitle: "Pompeji zerstört", desc: "Der Vulkan begräbt Pompeji und Herculaneum unter Asche und konserviert sie für die Nachwelt.", cat: "ereignis", imp: 2 },
            { id: 45, time: 105, title: "Papier erfunden", subtitle: "Cai Lun", desc: "Der chinesische Beamte Cai Lun verbessert die Papierherstellung grundlegend.", cat: "wissenschaft", imp: 2 },
            { id: 46, time: 313, title: "Mailänder Edikt", subtitle: "Konstantins Toleranz", desc: "Kaiser Konstantin gewährt Religionsfreiheit - das Christentum steigt zur Staatsreligion auf.", cat: "politik", imp: 2 },
            { id: 47, time: 476, title: "Fall Westroms", subtitle: "Ende der Antike", desc: "Der letzte weströmische Kaiser wird abgesetzt - Beginn des Mittelalters in Europa.", cat: "ereignis", imp: 1 },

            // Medieval
            { id: 48, time: 570, title: "Mohammed geboren", subtitle: "Prophet des Islam", desc: "Der Begründer des Islam wird in Mekka geboren.", cat: "person", imp: 1 },
            { id: 49, time: 622, title: "Hidschra", subtitle: "Beginn des Islam", desc: "Mohammed flieht von Mekka nach Medina - Beginn der islamischen Zeitrechnung.", cat: "ereignis", imp: 1 },
            { id: 50, time: 732, title: "Schlacht bei Tours", subtitle: "Karl Martell", desc: "Die Franken stoppen den islamischen Vormarsch in Europa.", cat: "ereignis", imp: 2 },
            { id: 51, time: 800, title: "Karl der Große", subtitle: "Kaiserkrönung", desc: "Karl wird in Rom zum Kaiser gekrönt - Grundstein für das Heilige Römische Reich.", cat: "politik", imp: 1 },
            { id: 52, time: 868, title: "Erstes gedrucktes Buch", subtitle: "Diamant-Sutra", desc: "Das älteste datierte gedruckte Buch entsteht in China.", cat: "kultur", imp: 2 },
            { id: 53, time: 1066, title: "Schlacht bei Hastings", subtitle: "Wilhelm der Eroberer", desc: "Die Normannen erobern England - tiefgreifende Veränderung der englischen Kultur.", cat: "ereignis", imp: 2 },
            { id: 54, time: 1096, title: "Erster Kreuzzug", subtitle: "Deus lo vult", desc: "Die Kreuzzüge beginnen - jahrhundertelange religiöse Konflikte zwischen Christentum und Islam.", cat: "ereignis", imp: 1 },
            { id: 55, time: 1215, title: "Magna Carta", subtitle: "Grundrechte", desc: "König Johann von England unterzeichnet die Magna Carta - Grundstein für konstitutionelle Rechte.", cat: "politik", imp: 2 },
            { id: 56, time: 1271, title: "Marco Polo reist nach China", subtitle: "Seidenstraße", desc: "Der venezianische Händler beginnt seine legendäre Reise an den Hof des Kublai Khan.", cat: "ereignis", imp: 2 },
            { id: 57, time: 1347, title: "Schwarzer Tod", subtitle: "Pest in Europa", desc: "Die Beulenpest tötet ein Drittel der europäischen Bevölkerung und verändert die Gesellschaft grundlegend.", cat: "ereignis", imp: 1 },
            { id: 58, time: 1431, title: "Jeanne d'Arc verbrannt", subtitle: "Märtyrerin", desc: "Die französische Nationalheldin wird als Ketzerin auf dem Scheiterhaufen verbrannt.", cat: "person", imp: 2 },
            { id: 59, time: 1453, title: "Fall Konstantinopels", subtitle: "Ende von Byzanz", desc: "Die Osmanen erobern Konstantinopel - das Ende des Oströmischen Reiches nach 1000 Jahren.", cat: "ereignis", imp: 1 },

            // Renaissance & Early Modern
            { id: 60, time: 1440, title: "Buchdruck", subtitle: "Gutenberg", desc: "Johannes Gutenberg erfindet den Buchdruck mit beweglichen Lettern - die Informationsrevolution beginnt.", cat: "wissenschaft", imp: 1 },
            { id: 61, time: 1452, title: "Leonardo da Vinci", subtitle: "Universalgenie", desc: "Das Renaissance-Genie wird geboren - Maler, Erfinder, Wissenschaftler in einer Person.", cat: "person", imp: 1 },
            { id: 62, time: 1473, title: "Kopernikus geboren", subtitle: "Astronom", desc: "Der Begründer des heliozentrischen Weltbildes wird in Thorn geboren.", cat: "person", imp: 2 },
            { id: 63, time: 1475, title: "Michelangelo geboren", subtitle: "Künstler", desc: "Einer der größten Künstler aller Zeiten - Schöpfer der Sixtinischen Decke.", cat: "person", imp: 2 },
            { id: 64, time: 1492, title: "Amerika entdeckt", subtitle: "Kolumbus", desc: "Christoph Kolumbus erreicht die Bahamas - der Beginn der europäischen Kolonisierung Amerikas.", cat: "ereignis", imp: 1 },
            { id: 65, time: 1498, title: "Seeweg nach Indien", subtitle: "Vasco da Gama", desc: "Der portugiesische Seefahrer erreicht Indien auf dem Seeweg um Afrika.", cat: "ereignis", imp: 2 },
            { id: 66, time: 1503, title: "Mona Lisa", subtitle: "Leonardo", desc: "Leonardo da Vinci beginnt das berühmteste Gemälde der Welt.", cat: "kultur", imp: 1 },
            { id: 67, time: 1508, title: "Sixtinische Kapelle", subtitle: "Michelangelo", desc: "Michelangelo beginnt die Ausmalung der Decke der Sixtinischen Kapelle.", cat: "kultur", imp: 2 },
            { id: 68, time: 1517, title: "95 Thesen", subtitle: "Luther", desc: "Martin Luther schlägt seine Thesen an - die Reformation beginnt und spaltet die Christenheit.", cat: "ereignis", imp: 1 },
            { id: 69, time: 1519, title: "Magellan-Expedition", subtitle: "Weltumsegelung", desc: "Die erste Weltumsegelung beginnt - der Beweis, dass die Erde eine Kugel ist.", cat: "ereignis", imp: 2 },
            { id: 70, time: 1543, title: "Heliozentrisches Weltbild", subtitle: "Kopernikus", desc: "Kopernikus veröffentlicht 'De revolutionibus' - die Erde ist nicht mehr Mittelpunkt des Universums.", cat: "wissenschaft", imp: 1 },
            { id: 71, time: 1564, title: "Shakespeare geboren", subtitle: "Dramatiker", desc: "Der größte Dichter der englischen Sprache wird in Stratford-upon-Avon geboren.", cat: "person", imp: 1 },
            { id: 72, time: 1564, title: "Galileo Galilei geboren", subtitle: "Wissenschaftler", desc: "Der Vater der modernen Naturwissenschaft wird in Pisa geboren.", cat: "person", imp: 2 },
            { id: 73, time: 1582, title: "Gregorianischer Kalender", subtitle: "Kalenderreform", desc: "Papst Gregor XIII. führt den bis heute gültigen Kalender ein.", cat: "wissenschaft", imp: 3 },
            { id: 74, time: 1600, title: "Giordano Bruno verbrannt", subtitle: "Ketzer", desc: "Der Philosoph wird wegen seiner Lehren vom unendlichen Universum hingerichtet.", cat: "person", imp: 3 },
            { id: 75, time: 1609, title: "Keplers Gesetze", subtitle: "Planetenbewegung", desc: "Johannes Kepler veröffentlicht seine Gesetze der Planetenbewegung.", cat: "wissenschaft", imp: 2 },
            { id: 76, time: 1610, title: "Galileos Teleskop", subtitle: "Jupiter-Monde", desc: "Galileo entdeckt mit seinem Teleskop die Monde des Jupiter.", cat: "wissenschaft", imp: 2 },
            { id: 77, time: 1618, title: "30-jähriger Krieg", subtitle: "Religionskrieg", desc: "Der verheerendste Krieg vor dem 20. Jahrhundert beginnt - Europa wird verwüstet.", cat: "ereignis", imp: 1 },
            { id: 78, time: 1637, title: "Descartes' Discours", subtitle: "Cogito ergo sum", desc: "'Ich denke, also bin ich' - Descartes begründet die moderne Philosophie.", cat: "wissenschaft", imp: 2 },
            { id: 79, time: 1642, title: "Newton geboren", subtitle: "Physiker", desc: "Der größte Wissenschaftler aller Zeiten wird in Woolsthorpe geboren.", cat: "person", imp: 1 },
            { id: 80, time: 1648, title: "Westfälischer Frieden", subtitle: "Ende des 30j. Krieges", desc: "Der Friedensvertrag beendet den 30-jährigen Krieg und begründet das moderne Völkerrecht.", cat: "politik", imp: 2 },
            { id: 81, time: 1687, title: "Newtons Principia", subtitle: "Physik", desc: "Newton veröffentlicht die Grundlagen der klassischen Mechanik und das Gravitationsgesetz.", cat: "wissenschaft", imp: 1 },

            // 18th Century
            { id: 82, time: 1685, title: "J.S. Bach geboren", subtitle: "Komponist", desc: "Der Meister des Barock wird in Eisenach geboren.", cat: "person", imp: 2 },
            { id: 83, time: 1694, title: "Voltaire geboren", subtitle: "Aufklärer", desc: "Der einflussreichste Denker der französischen Aufklärung.", cat: "person", imp: 2 },
            { id: 84, time: 1724, title: "Kant geboren", subtitle: "Philosoph", desc: "Immanuel Kant, der Begründer der kritischen Philosophie.", cat: "person", imp: 2 },
            { id: 85, time: 1751, title: "Encyclopédie", subtitle: "Diderot & d'Alembert", desc: "Das große Werk der Aufklärung beginnt zu erscheinen.", cat: "kultur", imp: 2 },
            { id: 86, time: 1756, title: "Mozart geboren", subtitle: "Wunderkind", desc: "Wolfgang Amadeus Mozart wird in Salzburg geboren.", cat: "person", imp: 1 },
            { id: 87, time: 1769, title: "Napoleon geboren", subtitle: "Kaiser", desc: "Der Mann, der Europa umgestalten wird, wird auf Korsika geboren.", cat: "person", imp: 1 },
            { id: 88, time: 1769, title: "Dampfmaschine", subtitle: "James Watt", desc: "Watt verbessert die Dampfmaschine entscheidend - die industrielle Revolution beginnt.", cat: "wissenschaft", imp: 1 },
            { id: 89, time: 1770, title: "Beethoven geboren", subtitle: "Komponist", desc: "Ludwig van Beethoven wird in Bonn geboren.", cat: "person", imp: 1 },
            { id: 90, time: 1776, title: "US-Unabhängigkeit", subtitle: "Declaration", desc: "Die USA erklären ihre Unabhängigkeit von Großbritannien - die erste moderne Demokratie entsteht.", cat: "politik", imp: 1 },
            { id: 91, time: 1781, title: "Kritik der reinen Vernunft", subtitle: "Kant", desc: "Kants Hauptwerk revolutioniert die Philosophie.", cat: "wissenschaft", imp: 2 },
            { id: 92, time: 1789, title: "Französische Revolution", subtitle: "Bastille", desc: "Der Sturm auf die Bastille - die Revolution verändert Europa für immer.", cat: "politik", imp: 1 },
            { id: 93, time: 1791, title: "Mozart stirbt", subtitle: "Wien", desc: "Das Musikgenie stirbt mit nur 35 Jahren - 600 Werke hinterlässt er.", cat: "person", imp: 2 },
            { id: 94, time: 1796, title: "Jenners Impfung", subtitle: "Pockenimpfung", desc: "Edward Jenner entwickelt die erste erfolgreiche Impfung der Geschichte.", cat: "wissenschaft", imp: 2 },

            // 19th Century
            { id: 95, time: 1804, title: "Napoleon Kaiser", subtitle: "Kaiserkrönung", desc: "Napoleon krönt sich selbst zum Kaiser der Franzosen.", cat: "politik", imp: 2 },
            { id: 96, time: 1805, title: "Trafalgar", subtitle: "Seeschlacht", desc: "Nelson besiegt die französisch-spanische Flotte und sichert Britanniens Seeherrschaft.", cat: "ereignis", imp: 2 },
            { id: 97, time: 1815, title: "Waterloo", subtitle: "Napoleons Ende", desc: "Napoleon wird endgültig besiegt - das Ende einer Ära.", cat: "ereignis", imp: 1 },
            { id: 98, time: 1818, title: "Marx geboren", subtitle: "Philosoph", desc: "Karl Marx, der Begründer des wissenschaftlichen Sozialismus.", cat: "person", imp: 2 },
            { id: 99, time: 1824, title: "9. Symphonie", subtitle: "Beethoven", desc: "Beethovens monumentales Werk mit der Ode an die Freude wird uraufgeführt.", cat: "kultur", imp: 2 },
            { id: 100, time: 1831, title: "Darwin auf der Beagle", subtitle: "Forschungsreise", desc: "Charles Darwin beginnt seine Reise, die zur Evolutionstheorie führen wird.", cat: "wissenschaft", imp: 2 },
            { id: 101, time: 1837, title: "Viktorianisches Zeitalter", subtitle: "Queen Victoria", desc: "Victoria wird Königin - Beginn einer prägenden Epoche.", cat: "politik", imp: 2 },
            { id: 102, time: 1839, title: "Fotografie erfunden", subtitle: "Daguerre", desc: "Louis Daguerre stellt die Daguerreotypie vor - die Welt kann festgehalten werden.", cat: "wissenschaft", imp: 2 },
            { id: 103, time: 1848, title: "Kommunistisches Manifest", subtitle: "Marx & Engels", desc: "'Ein Gespenst geht um in Europa' - das Manifest verändert die Politik.", cat: "politik", imp: 1 },
            { id: 104, time: 1848, title: "Märzrevolution", subtitle: "Europa revoltiert", desc: "Revolutionen erschüttern ganz Europa - der Ruf nach Freiheit und Demokratie.", cat: "politik", imp: 2 },
            { id: 105, time: 1859, title: "Evolutionstheorie", subtitle: "Darwin", desc: "'Die Entstehung der Arten' erscheint und revolutioniert unser Verständnis des Lebens.", cat: "wissenschaft", imp: 1 },
            { id: 106, time: 1861, title: "Amerikanischer Bürgerkrieg", subtitle: "Union vs. Konföderation", desc: "Der blutigste Krieg Amerikas beginnt - um Sklaverei und Einheit der Nation.", cat: "ereignis", imp: 2 },
            { id: 107, time: 1865, title: "Lincoln ermordet", subtitle: "Ford's Theatre", desc: "Abraham Lincoln wird erschossen - kurz nach Ende des Bürgerkriegs.", cat: "ereignis", imp: 2 },
            { id: 108, time: 1869, title: "Periodensystem", subtitle: "Mendelejew", desc: "Dmitri Mendelejew ordnet die Elemente - eine Revolution der Chemie.", cat: "wissenschaft", imp: 2 },

            // Impressionism Era
            { id: 109, time: 1840, title: "Monet geboren", subtitle: "Impressionist", desc: "Claude Monet, der Begründer des Impressionismus, wird in Paris geboren.", cat: "person", imp: 2 },
            { id: 110, time: 1841, title: "Renoir geboren", subtitle: "Impressionist", desc: "Pierre-Auguste Renoir, Meister des Lichts und der Farbe.", cat: "person", imp: 3 },
            { id: 111, time: 1853, title: "Van Gogh geboren", subtitle: "Post-Impressionist", desc: "Vincent van Gogh, dessen tragisches Leben unsterbliche Kunst hervorbrachte.", cat: "person", imp: 2 },
            { id: 112, time: 1855, title: "Das Atelier des Malers", subtitle: "Courbet", desc: "Gustave Courbets programmatisches Werk des Realismus.", cat: "kultur", imp: 3 },
            { id: 113, time: 1863, title: "Frühstück im Grünen", subtitle: "Manet", desc: "Édouard Manets skandalöses Gemälde schockiert den Pariser Salon.", cat: "kultur", imp: 2 },
            { id: 114, time: 1869, title: "La Grenouillère", subtitle: "Monet & Renoir", desc: "Monet und Renoir malen gemeinsam - die Geburtsstunde des Impressionismus.", cat: "kultur", imp: 3 },
            { id: 115, time: 1872, title: "Impression, Sonnenaufgang", subtitle: "Monet", desc: "Das namensgebende Werk des Impressionismus - ein Hafen im Morgennebel.", cat: "kultur", imp: 1 },
            { id: 116, time: 1874, title: "Erste Impressionisten-Ausstellung", subtitle: "Paris", desc: "Monet, Renoir, Degas, Pissarro und andere stellen aus - ein Skandal und eine Revolution.", cat: "kultur", imp: 1 },
            { id: 117, time: 1876, title: "Telefon erfunden", subtitle: "Alexander Graham Bell", desc: "Das Telefon revolutioniert die Kommunikation der Menschheit.", cat: "wissenschaft", imp: 1 },
            { id: 118, time: 1877, title: "Phonograph", subtitle: "Edison", desc: "Thomas Edison erfindet den Phonographen - Klang kann aufgezeichnet werden.", cat: "wissenschaft", imp: 2 },
            { id: 119, time: 1879, title: "Glühbirne", subtitle: "Edison", desc: "Edison präsentiert die praktische Glühbirne - elektrisches Licht verändert den Alltag.", cat: "wissenschaft", imp: 1 },
            { id: 120, time: 1880, title: "Der Denker", subtitle: "Rodin", desc: "Auguste Rodin beginnt seine berühmteste Skulptur.", cat: "kultur", imp: 3 },
            { id: 121, time: 1881, title: "Picasso geboren", subtitle: "Künstler", desc: "Pablo Picasso, der einflussreichste Künstler des 20. Jahrhunderts.", cat: "person", imp: 1 },
            { id: 122, time: 1883, title: "Orient-Express", subtitle: "Erste Fahrt", desc: "Der legendäre Luxuszug verbindet Paris mit Konstantinopel.", cat: "ereignis", imp: 3 },
            { id: 123, time: 1886, title: "Grande Jatte", subtitle: "Seurat", desc: "Georges Seurat vollendet sein Meisterwerk des Pointillismus.", cat: "kultur", imp: 2 },
            { id: 124, time: 1886, title: "Freiheitsstatue", subtitle: "New York", desc: "Das Geschenk Frankreichs wird im Hafen von New York eingeweiht.", cat: "kultur", imp: 2 },
            { id: 125, time: 1888, title: "Sternennacht", subtitle: "Van Gogh", desc: "Van Gogh malt in Saint-Rémy sein berühmtestes Werk.", cat: "kultur", imp: 1 },
            { id: 126, time: 1889, title: "Eiffelturm", subtitle: "Paris", desc: "Zur Weltausstellung wird das 324m hohe Wahrzeichen eingeweiht.", cat: "kultur", imp: 1 },
            { id: 127, time: 1890, title: "Van Gogh stirbt", subtitle: "Auvers-sur-Oise", desc: "Das verkannte Genie stirbt mit nur 37 Jahren.", cat: "person", imp: 2 },
            { id: 128, time: 1893, title: "Der Schrei", subtitle: "Edvard Munch", desc: "Munchs expressionistisches Meisterwerk drückt existentielle Angst aus.", cat: "kultur", imp: 1 },
            { id: 129, time: 1895, title: "Erster Film", subtitle: "Lumière-Brüder", desc: "Die Geburt des Kinos - 'Arbeiter verlassen die Lumière-Werke' wird gezeigt.", cat: "kultur", imp: 1 },
            { id: 130, time: 1895, title: "Röntgenstrahlen", subtitle: "Wilhelm Röntgen", desc: "Die Entdeckung revolutioniert die Medizin - man kann ins Innere des Körpers blicken.", cat: "wissenschaft", imp: 1 },
            { id: 131, time: 1896, title: "Erste Olympiade der Neuzeit", subtitle: "Athen", desc: "Die modernen Olympischen Spiele werden in Athen wiederbelebt.", cat: "ereignis", imp: 2 },
            { id: 132, time: 1897, title: "Drahtlose Telegrafie", subtitle: "Marconi", desc: "Guglielmo Marconi sendet Signale über den Atlantik.", cat: "wissenschaft", imp: 2 },
            { id: 133, time: 1900, title: "Der Kuss", subtitle: "Gustav Klimt", desc: "Klimts goldenes Meisterwerk des Jugendstils.", cat: "kultur", imp: 2 },
            { id: 134, time: 1900, title: "Traumdeutung", subtitle: "Sigmund Freud", desc: "Freud veröffentlicht sein Hauptwerk - die Geburt der Psychoanalyse.", cat: "wissenschaft", imp: 1 },
            { id: 135, time: 1900, title: "Quantenhypothese", subtitle: "Max Planck", desc: "Planck begründet die Quantenphysik - eine Revolution des Weltbildes.", cat: "wissenschaft", imp: 2 },

            // 20th Century
            { id: 136, time: 1903, title: "Erster Motorflug", subtitle: "Wright-Brüder", desc: "Der Mensch fliegt zum ersten Mal kontrolliert - 12 Sekunden, 37 Meter.", cat: "wissenschaft", imp: 1 },
            { id: 137, time: 1905, title: "Relativitätstheorie", subtitle: "Albert Einstein", desc: "E=mc² - Einstein revolutioniert unser Verständnis von Raum, Zeit und Energie.", cat: "wissenschaft", imp: 1 },
            { id: 138, time: 1905, title: "Russische Revolution", subtitle: "Blutsonntag", desc: "Die erste russische Revolution erschüttert das Zarenreich.", cat: "politik", imp: 2 },
            { id: 139, time: 1907, title: "Demoiselles d'Avignon", subtitle: "Picasso", desc: "Picassos revolutionäres Werk begründet den Kubismus.", cat: "kultur", imp: 1 },
            { id: 140, time: 1908, title: "Ford Model T", subtitle: "Massenproduktion", desc: "Henry Ford beginnt die Fließbandproduktion - das Auto für jedermann.", cat: "wissenschaft", imp: 2 },
            { id: 141, time: 1912, title: "Titanic sinkt", subtitle: "Nordatlantik", desc: "Das 'unsinkbare' Schiff geht unter - 1.500 Menschen sterben.", cat: "ereignis", imp: 1 },
            { id: 142, time: 1913, title: "Frühlingsopfer", subtitle: "Strawinsky", desc: "Strawinskys Ballett löst einen Skandal aus und revolutioniert die Musik.", cat: "kultur", imp: 2 },
            { id: 143, time: 1914, title: "Erster Weltkrieg", subtitle: "Sarajevo", desc: "Die Ermordung von Erzherzog Franz Ferdinand löst die 'Urkatastrophe des 20. Jahrhunderts' aus.", cat: "ereignis", imp: 1 },
            { id: 144, time: 1915, title: "Allgemeine Relativitätstheorie", subtitle: "Einstein", desc: "Einstein vollendet seine Theorie der Gravitation - Raum und Zeit sind gekrümmt.", cat: "wissenschaft", imp: 2 },
            { id: 145, time: 1916, title: "Schlacht an der Somme", subtitle: "1 Million Tote", desc: "Eine der verlustreichsten Schlachten der Geschichte.", cat: "ereignis", imp: 2 },
            { id: 146, time: 1917, title: "Russische Revolution", subtitle: "Lenin ergreift Macht", desc: "Die Bolschewiki stürzen die Provisorische Regierung - der Kommunismus siegt.", cat: "politik", imp: 1 },
            { id: 147, time: 1918, title: "Kriegsende", subtitle: "11. November", desc: "Der Erste Weltkrieg endet - 17 Millionen Tote, eine zerstörte Weltordnung.", cat: "ereignis", imp: 1 },
            { id: 148, time: 1918, title: "Spanische Grippe", subtitle: "Pandemie", desc: "Die Grippe-Pandemie tötet mehr Menschen als der Krieg - bis zu 50 Millionen.", cat: "ereignis", imp: 2 },
            { id: 149, time: 1919, title: "Bauhaus gegründet", subtitle: "Walter Gropius", desc: "Die revolutionäre Designschule in Weimar vereint Kunst und Handwerk.", cat: "kultur", imp: 1 },
            { id: 150, time: 1920, title: "Frauenwahlrecht USA", subtitle: "19. Amendment", desc: "Amerikanische Frauen erhalten endlich das Wahlrecht.", cat: "politik", imp: 2 },
            { id: 151, time: 1922, title: "Tutanchamuns Grab", subtitle: "Howard Carter", desc: "Die Entdeckung des unberührten Pharaonengrabs fasziniert die Welt.", cat: "ereignis", imp: 2 },
            { id: 152, time: 1924, title: "Stalin an der Macht", subtitle: "Sowjetunion", desc: "Nach Lenins Tod übernimmt Stalin die Führung.", cat: "politik", imp: 2 },
            { id: 153, time: 1927, title: "Lindberghs Atlantikflug", subtitle: "Spirit of St. Louis", desc: "Der erste Non-Stop-Flug über den Atlantik von New York nach Paris.", cat: "ereignis", imp: 2 },
            { id: 154, time: 1928, title: "Penicillin", subtitle: "Alexander Fleming", desc: "Fleming entdeckt das erste Antibiotikum - eine Revolution der Medizin.", cat: "wissenschaft", imp: 1 },
            { id: 155, time: 1929, title: "Börsencrash", subtitle: "Schwarzer Freitag", desc: "Der Zusammenbruch der Wall Street löst die Weltwirtschaftskrise aus.", cat: "ereignis", imp: 1 },
            { id: 156, time: 1929, title: "Museum of Modern Art", subtitle: "New York", desc: "Das MoMA öffnet und wird zum wichtigsten Museum moderner Kunst.", cat: "kultur", imp: 3 },
            { id: 157, time: 1933, title: "Hitler Reichskanzler", subtitle: "NS-Diktatur beginnt", desc: "Adolf Hitler wird zum Reichskanzler ernannt - der Weg in die Katastrophe.", cat: "politik", imp: 1 },
            { id: 158, time: 1933, title: "Bücherverbrennungen", subtitle: "Nazi-Deutschland", desc: "Die Nazis verbrennen 'undeutsche' Bücher - ein Zeichen kommender Barbarei.", cat: "ereignis", imp: 2 },
            { id: 159, time: 1936, title: "Spanischer Bürgerkrieg", subtitle: "Franco vs. Republik", desc: "Der Vorspiel zum Zweiten Weltkrieg - faschistische gegen demokratische Kräfte.", cat: "ereignis", imp: 2 },
            { id: 160, time: 1937, title: "Guernica", subtitle: "Picasso", desc: "Picassos Anti-Kriegs-Meisterwerk als Reaktion auf die Bombardierung der Stadt.", cat: "kultur", imp: 1 },
            { id: 161, time: 1938, title: "Reichspogromnacht", subtitle: "Novemberpogrome", desc: "Organisierte Gewalt gegen Juden in Deutschland - der Auftakt zum Holocaust.", cat: "ereignis", imp: 1 },
            { id: 162, time: 1939, title: "Zweiter Weltkrieg", subtitle: "Überfall auf Polen", desc: "Der verheerendste Krieg der Geschichte beginnt mit dem deutschen Angriff.", cat: "ereignis", imp: 1 },
            { id: 163, time: 1941, title: "Pearl Harbor", subtitle: "USA treten ein", desc: "Japan greift an - Amerika tritt in den Krieg ein.", cat: "ereignis", imp: 2 },
            { id: 164, time: 1942, title: "Wannseekonferenz", subtitle: "Holocaust", desc: "Die Nazis planen die systematische Ermordung der europäischen Juden.", cat: "ereignis", imp: 1 },
            { id: 165, time: 1944, title: "D-Day", subtitle: "Landung in der Normandie", desc: "Die größte amphibische Operation der Geschichte - die Befreiung Europas beginnt.", cat: "ereignis", imp: 1 },
            { id: 166, time: 1945, title: "Hiroshima", subtitle: "Atombombe", desc: "Die erste Atombombe auf eine Stadt tötet 80.000 Menschen sofort.", cat: "ereignis", imp: 1 },
            { id: 167, time: 1945, title: "Kriegsende", subtitle: "8. Mai / 15. August", desc: "Der Zweite Weltkrieg endet - 60 Millionen Tote, die Welt ist verändert.", cat: "ereignis", imp: 1 },
            { id: 168, time: 1945, title: "Vereinte Nationen", subtitle: "UN gegründet", desc: "Die UN wird gegründet, um künftige Kriege zu verhindern.", cat: "politik", imp: 2 },
            { id: 169, time: 1947, title: "Indien unabhängig", subtitle: "Ende der Kolonialzeit", desc: "Indien und Pakistan werden unabhängig - die Entkolonialisierung beginnt.", cat: "politik", imp: 2 },
            { id: 170, time: 1948, title: "Menschenrechtserklärung", subtitle: "UN", desc: "Die Allgemeine Erklärung der Menschenrechte wird verabschiedet.", cat: "politik", imp: 1 },
            { id: 171, time: 1948, title: "Gründung Israels", subtitle: "Naher Osten", desc: "Der Staat Israel wird ausgerufen - der Beginn des Nahostkonflikts.", cat: "politik", imp: 2 },
            { id: 172, time: 1949, title: "NATO gegründet", subtitle: "Westliche Allianz", desc: "Das nordatlantische Verteidigungsbündnis entsteht.", cat: "politik", imp: 2 },
            { id: 173, time: 1949, title: "Volksrepublik China", subtitle: "Mao Zedong", desc: "Die Kommunisten siegen im Bürgerkrieg - China wird kommunistisch.", cat: "politik", imp: 1 },
            { id: 174, time: 1950, title: "Koreakrieg", subtitle: "Kalter Krieg wird heiß", desc: "Der erste Stellvertreterkrieg des Kalten Krieges beginnt.", cat: "ereignis", imp: 2 },
            { id: 175, time: 1953, title: "DNA-Struktur", subtitle: "Watson & Crick", desc: "Die Doppelhelix-Struktur der DNA wird entdeckt - das Geheimnis des Lebens.", cat: "wissenschaft", imp: 1 },
            { id: 176, time: 1954, title: "Rock 'n' Roll", subtitle: "Elvis Presley", desc: "Elvis' erste Aufnahmen - die Geburt einer Jugendkultur.", cat: "kultur", imp: 2 },
            { id: 177, time: 1955, title: "Rosa Parks", subtitle: "Bürgerrechtsbewegung", desc: "Rosa Parks weigert sich aufzustehen - der Montgomery Bus Boycott beginnt.", cat: "politik", imp: 2 },
            { id: 178, time: 1957, title: "Sputnik", subtitle: "Erster Satellit", desc: "Die Sowjetunion schießt den ersten Satelliten ins All - das Weltraumzeitalter beginnt.", cat: "wissenschaft", imp: 1 },
            { id: 179, time: 1957, title: "Römische Verträge", subtitle: "EWG gegründet", desc: "Die Europäische Wirtschaftsgemeinschaft wird gegründet - Grundstein der EU.", cat: "politik", imp: 2 },
            { id: 180, time: 1959, title: "Kubanische Revolution", subtitle: "Castro siegt", desc: "Fidel Castro stürzt Batista - Kuba wird kommunistisch.", cat: "politik", imp: 2 },
            { id: 181, time: 1961, title: "Berliner Mauer", subtitle: "Teilung Deutschlands", desc: "Die Mauer teilt Berlin und symbolisiert den Eisernen Vorhang.", cat: "ereignis", imp: 1 },
            { id: 182, time: 1961, title: "Gagarin im All", subtitle: "Erster Mensch", desc: "Juri Gagarin umrundet als erster Mensch die Erde.", cat: "wissenschaft", imp: 1 },
            { id: 183, time: 1962, title: "Kubakrise", subtitle: "Am Rand des Atomkriegs", desc: "Die Welt steht am Rand der nuklearen Vernichtung.", cat: "ereignis", imp: 1 },
            { id: 184, time: 1962, title: "Marilyn Monroe stirbt", subtitle: "Hollywood-Ikone", desc: "Der mysteriöse Tod der größten Filmikone ihrer Zeit.", cat: "person", imp: 3 },
            { id: 185, time: 1963, title: "Kennedy ermordet", subtitle: "Dallas", desc: "JFK wird erschossen - ein Trauma für Amerika.", cat: "ereignis", imp: 1 },
            { id: 186, time: 1963, title: "I Have a Dream", subtitle: "Martin Luther King", desc: "Kings historische Rede beim Marsch auf Washington.", cat: "politik", imp: 1 },
            { id: 187, time: 1964, title: "Beatles in Amerika", subtitle: "British Invasion", desc: "Die Beatles erobern Amerika - die Musikwelt verändert sich.", cat: "kultur", imp: 2 },
            { id: 188, time: 1965, title: "Vietnamkrieg eskaliert", subtitle: "US-Bodentruppen", desc: "Amerika verstrickt sich tiefer in den Vietnamkrieg.", cat: "ereignis", imp: 2 },
            { id: 189, time: 1968, title: "MLK ermordet", subtitle: "Memphis", desc: "Martin Luther King wird erschossen - Unruhen erschüttern Amerika.", cat: "ereignis", imp: 1 },
            { id: 190, time: 1968, title: "68er-Bewegung", subtitle: "Weltweite Proteste", desc: "Studentenproteste erschüttern Paris, Berlin, Prag und die Welt.", cat: "politik", imp: 2 },
            { id: 191, time: 1969, title: "Mondlandung", subtitle: "Apollo 11", desc: "'Ein kleiner Schritt für einen Menschen...' - der Mensch betritt den Mond.", cat: "wissenschaft", imp: 1 },
            { id: 192, time: 1969, title: "Woodstock", subtitle: "Festival", desc: "Das legendäre Festival definiert eine Generation.", cat: "kultur", imp: 2 },
            { id: 193, time: 1971, title: "Ende des Goldstandards", subtitle: "Nixon-Schock", desc: "Der Dollar ist nicht mehr durch Gold gedeckt - das Ende von Bretton Woods.", cat: "politik", imp: 3 },
            { id: 194, time: 1973, title: "Ölkrise", subtitle: "OPEC-Embargo", desc: "Die Ölkrise erschüttert die westlichen Volkswirtschaften.", cat: "ereignis", imp: 2 },
            { id: 195, time: 1974, title: "Nixon tritt zurück", subtitle: "Watergate", desc: "Der Watergate-Skandal zwingt Nixon zum Rücktritt.", cat: "politik", imp: 2 },
            { id: 196, time: 1975, title: "Ende Vietnamkrieg", subtitle: "Fall Saigons", desc: "Der letzte Hubschrauber verlässt Saigon - Amerika hat verloren.", cat: "ereignis", imp: 2 },
            { id: 197, time: 1976, title: "Apple gegründet", subtitle: "Jobs & Wozniak", desc: "In einer Garage beginnt die Personal-Computer-Revolution.", cat: "wissenschaft", imp: 2 },
            { id: 198, time: 1977, title: "Star Wars", subtitle: "George Lucas", desc: "Der Film verändert Hollywood und die Popkultur für immer.", cat: "kultur", imp: 2 },
            { id: 199, time: 1979, title: "Iranische Revolution", subtitle: "Khomeini", desc: "Der Schah wird gestürzt - Iran wird zur Islamischen Republik.", cat: "politik", imp: 2 },
            { id: 200, time: 1981, title: "AIDS identifiziert", subtitle: "Pandemie beginnt", desc: "Die erste AIDS-Fälle werden erkannt - eine neue Seuche.", cat: "wissenschaft", imp: 2 },
            { id: 201, time: 1981, title: "IBM PC", subtitle: "Personal Computer", desc: "Der IBM PC wird zum Standard - Computer für jeden.", cat: "wissenschaft", imp: 2 },
            { id: 202, time: 1985, title: "Gorbatschow", subtitle: "Glasnost & Perestroika", desc: "Der neue sowjetische Führer beginnt Reformen.", cat: "politik", imp: 2 },
            { id: 203, time: 1986, title: "Tschernobyl", subtitle: "Nuklearkatastrophe", desc: "Der GAU im Atomkraftwerk - die schlimmste Nuklearkatastrophe der Geschichte.", cat: "ereignis", imp: 1 },
            { id: 204, time: 1989, title: "Tiananmen", subtitle: "Massaker in Peking", desc: "Die chinesische Demokratiebewegung wird brutal niedergeschlagen.", cat: "ereignis", imp: 2 },
            { id: 205, time: 1989, title: "Mauerfall", subtitle: "9. November", desc: "Die Berliner Mauer fällt - das Ende des Kalten Krieges beginnt.", cat: "ereignis", imp: 1 },
            { id: 206, time: 1990, title: "Deutsche Einheit", subtitle: "3. Oktober", desc: "Deutschland ist nach 45 Jahren wieder vereint.", cat: "politik", imp: 2 },
            { id: 207, time: 1990, title: "Hubble-Teleskop", subtitle: "Weltraumteleskop", desc: "Das Teleskop revolutioniert unseren Blick ins All.", cat: "wissenschaft", imp: 2 },
            { id: 208, time: 1991, title: "Ende der UdSSR", subtitle: "Kalter Krieg vorbei", desc: "Die Sowjetunion löst sich auf - das Ende einer Supermacht.", cat: "politik", imp: 1 },
            { id: 209, time: 1991, title: "World Wide Web", subtitle: "Tim Berners-Lee", desc: "Das WWW wird öffentlich - der Beginn des Internet-Zeitalters.", cat: "wissenschaft", imp: 1 },
            { id: 210, time: 1993, title: "Maastricht-Vertrag", subtitle: "EU gegründet", desc: "Die Europäische Union entsteht.", cat: "politik", imp: 2 },
            { id: 211, time: 1994, title: "Mandela Präsident", subtitle: "Ende der Apartheid", desc: "Nelson Mandela wird der erste schwarze Präsident Südafrikas.", cat: "politik", imp: 1 },
            { id: 212, time: 1997, title: "Dolly das Schaf", subtitle: "Erstes Klon-Säugetier", desc: "Das erste geklonte Säugetier wirft ethische Fragen auf.", cat: "wissenschaft", imp: 2 },
            { id: 213, time: 1997, title: "Prinzessin Diana stirbt", subtitle: "Paris", desc: "Der tragische Unfalltod erschüttert die Welt.", cat: "ereignis", imp: 2 },
            { id: 214, time: 1998, title: "Google gegründet", subtitle: "Suchmaschine", desc: "Page und Brin gründen Google - die Informationsrevolution.", cat: "wissenschaft", imp: 2 },

            // 21st Century
            { id: 215, time: 2001, title: "9/11", subtitle: "Terroranschläge", desc: "Die Anschläge auf das World Trade Center verändern die Welt.", cat: "ereignis", imp: 1 },
            { id: 216, time: 2001, title: "Wikipedia", subtitle: "Freies Wissen", desc: "Die freie Enzyklopädie wird gestartet.", cat: "wissenschaft", imp: 3 },
            { id: 217, time: 2003, title: "Irakkrieg", subtitle: "Sturz Saddams", desc: "Die USA stürzen Saddam Hussein - ein kontroverser Krieg.", cat: "ereignis", imp: 2 },
            { id: 218, time: 2004, title: "Facebook", subtitle: "Social Media", desc: "Mark Zuckerberg gründet Facebook - soziale Medien entstehen.", cat: "wissenschaft", imp: 2 },
            { id: 219, time: 2004, title: "Tsunami Asien", subtitle: "230.000 Tote", desc: "Eine der tödlichsten Naturkatastrophen der Geschichte.", cat: "ereignis", imp: 2 },
            { id: 220, time: 2007, title: "iPhone", subtitle: "Smartphone-Revolution", desc: "Apple revolutioniert mit dem iPhone die mobile Kommunikation.", cat: "wissenschaft", imp: 1 },
            { id: 221, time: 2008, title: "Finanzkrise", subtitle: "Lehman Brothers", desc: "Die größte Wirtschaftskrise seit 1929 erschüttert die Welt.", cat: "ereignis", imp: 1 },
            { id: 222, time: 2008, title: "Obama gewählt", subtitle: "Erster schwarzer Präsident", desc: "Barack Obama wird als erster Afroamerikaner US-Präsident.", cat: "politik", imp: 2 },
            { id: 223, time: 2010, title: "Arabischer Frühling", subtitle: "Revolutionen beginnen", desc: "Protestwellen erfassen die arabische Welt.", cat: "politik", imp: 2 },
            { id: 224, time: 2011, title: "Fukushima", subtitle: "Nuklearkatastrophe", desc: "Ein Tsunami löst die schlimmste Nuklearkatastrophe seit Tschernobyl aus.", cat: "ereignis", imp: 2 },
            { id: 225, time: 2011, title: "Bin Laden getötet", subtitle: "US-Operation", desc: "Der Anführer von Al-Qaida wird in Pakistan getötet.", cat: "ereignis", imp: 2 },
            { id: 226, time: 2012, title: "Higgs-Boson", subtitle: "CERN", desc: "Das 'Gottesteilchen' wird am CERN nachgewiesen.", cat: "wissenschaft", imp: 2 },
            { id: 227, time: 2013, title: "Snowden-Enthüllungen", subtitle: "NSA-Überwachung", desc: "Edward Snowden enthüllt das Ausmaß der globalen Überwachung.", cat: "politik", imp: 2 },
            { id: 228, time: 2014, title: "Krim-Annexion", subtitle: "Russland", desc: "Russland annektiert die Krim - eine neue Ära der Konfrontation.", cat: "politik", imp: 2 },
            { id: 229, time: 2015, title: "Flüchtlingskrise", subtitle: "Europa", desc: "Millionen Flüchtlinge kommen nach Europa.", cat: "ereignis", imp: 2 },
            { id: 230, time: 2015, title: "Pariser Klimaabkommen", subtitle: "COP21", desc: "195 Staaten einigen sich auf Klimaziele.", cat: "politik", imp: 2 },
            { id: 231, time: 2016, title: "Brexit", subtitle: "UK verlässt EU", desc: "Großbritannien stimmt für den Austritt aus der EU.", cat: "politik", imp: 2 },
            { id: 232, time: 2016, title: "Trump gewählt", subtitle: "US-Präsident", desc: "Donald Trump wird überraschend zum US-Präsidenten gewählt.", cat: "politik", imp: 2 },
            { id: 233, time: 2017, title: "Gravitationswellen", subtitle: "LIGO", desc: "Erstmals werden Gravitationswellen direkt nachgewiesen - Einstein bestätigt.", cat: "wissenschaft", imp: 2 },
            { id: 234, time: 2019, title: "Erstes Bild Schwarzes Loch", subtitle: "Event Horizon", desc: "Das erste Foto eines schwarzen Lochs wird veröffentlicht.", cat: "wissenschaft", imp: 2 },
            { id: 235, time: 2020, title: "COVID-19", subtitle: "Pandemie", desc: "Das Coronavirus legt die Welt lahm - die größte Pandemie seit 1918.", cat: "ereignis", imp: 1 },
            { id: 236, time: 2020, title: "George Floyd", subtitle: "Black Lives Matter", desc: "Sein Tod löst weltweite Proteste gegen Rassismus aus.", cat: "ereignis", imp: 2 },
            { id: 237, time: 2021, title: "Sturm auf das Kapitol", subtitle: "6. Januar", desc: "Trump-Anhänger stürmen das US-Kapitol.", cat: "ereignis", imp: 2 },
            { id: 238, time: 2021, title: "Taliban übernehmen", subtitle: "Afghanistan", desc: "Nach 20 Jahren Krieg übernehmen die Taliban erneut die Macht.", cat: "politik", imp: 2 },
            { id: 239, time: 2022, title: "Ukraine-Krieg", subtitle: "Russische Invasion", desc: "Russland greift die Ukraine an - der größte Krieg in Europa seit 1945.", cat: "ereignis", imp: 1 },
            { id: 240, time: 2022, title: "James Webb Teleskop", subtitle: "Erste Bilder", desc: "Das leistungsstärkste Weltraumteleskop zeigt das frühe Universum.", cat: "wissenschaft", imp: 2 },
            { id: 241, time: 2022, title: "Queen Elizabeth II. stirbt", subtitle: "70 Jahre Herrschaft", desc: "Die am längsten regierende britische Monarchin stirbt mit 96.", cat: "person", imp: 2 },
            { id: 242, time: 2023, title: "ChatGPT", subtitle: "KI-Revolution", desc: "Künstliche Intelligenz wird Mainstream - eine neue Ära beginnt.", cat: "wissenschaft", imp: 1 },
            { id: 243, time: 2023, title: "Hamas-Angriff", subtitle: "Nahostkonflikt", desc: "Der überraschende Angriff löst einen neuen Krieg in Gaza aus.", cat: "ereignis", imp: 2 },
            { id: 244, time: 2024, title: "Superwahljahr", subtitle: "Globale Wahlen", desc: "In über 60 Ländern finden Wahlen statt - die Hälfte der Menschheit wählt.", cat: "politik", imp: 2 }
        ];

        // ============================================
        // ZOOM LEVELS
        // ============================================
        const zoomLevels = [
            { halfRange: 14000000000, maxImp: 1, name: "Kosmisch" },
            { halfRange: 500000000, maxImp: 1, name: "Geologisch" },
            { halfRange: 50000000, maxImp: 1, name: "Erdgeschichte" },
            { halfRange: 2000000, maxImp: 1, name: "Prähistorisch" },
            { halfRange: 50000, maxImp: 1, name: "Urzeit" },
            { halfRange: 3000, maxImp: 1, name: "Geschichte" },
            { halfRange: 800, maxImp: 2, name: "Epochen" },
            { halfRange: 200, maxImp: 2, name: "Jahrhundert" },
            { halfRange: 50, maxImp: 3, name: "Detailliert" },
            { halfRange: 15, maxImp: 3, name: "Fein" }
        ];

